

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: